name: small_action
outputs:
  testoutput: ${{ runs.mytestoutput.outputs.MSG}}
inputs:
  pipname:
    required: true
    type: string
runs:
  uses: 'composite'
  steps:
    - name: Checkout action at unit-test job
        uses: actions/checkout@v4
    - name: Install ${{ inputs.pipname}}
        run: pip3 install ${{ inputs.pipname}}
    - name: This is example output
      id: mytestoutput
      run: "echo MSG=HelloWorld >> $GITHUB_OUTPUT"