name: small_action
inputs:
  pipname:
    required: true
    type: string

runs:
  uses: "composite"
  steps:
    - name: Install ${{inputs.pipname}}
      run: pip3 install ${{inputs.pipname}}
      shell: bash
