name: deployme
on:
  workflow_call:
    outputs:
      mynodeoutput:
        value: ${{jobs.reusejob.outputs.node_status}}
    inputs:
      token:
        type: string
        required: true
      environment:
        type: string
        required: true
        default: dev
      mychoice:
        type: string
        required: true
    
jobs:
  reusejob:
    runs-on: ubuntu-latest
    
    outputs:
      node_status: ${{steps.node.outputs.NODE_STATUS}}
    environment:
      name: ${{ inputs.environment }}
      url: https://amitapppod-service-amit-${{vars.ENV_NAME}}.apps.opc-sonf-ogn.orange-guinee.com/?input=green

    steps:
    - name: Checkout action at jobs
      uses: actions/checkout@v4
    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        source: "github"
        github_pat: "${{github.token}}"
        kam: "latest"
    - name: Setup oc
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: https://api.opc-sonf-ogn.orange-guinee.com:6443
        openshift_token: ${{inputs.token}}
    - name: Get node info
      id: node
      run: echo "NODE_STATUS=$(oc get nodes|grep master-0|sed 's/[ \t]\+/|/gi'|cut -d'|' -f2)" >> $GITHUB_OUTPUT

    - name: Replacing image name in kubernetes/development/deployment.yaml
      uses:  cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '_{_'
        tokenSuffix: '_}_'
        files: '["kubernetes/development/deployment.yaml"]'
      env:
        imagename: ${{vars.DOCKERHUB_USERNAME}}/myworkflowappqsimage-${{github.sha}}
        mychoice: ${{inputs.mychoice}}
        ENV_NAME: ${{ vars.ENV_NAME}}
        NODE_PORT: ${{vars.NODE_PORT}}
    - name: Deploy now
      run: oc apply -f kubernetes/development/deployment.yaml 