name: app workflow
env:
  choice: Indian
on: 
  workflow_dispatch:
  push:
    branches:
    - main
    - mybranch
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action at unit-test job
      uses: actions/checkout@v4
    - name: Install flask
      run: pip3 install flask
    - name: Run app
      run: python3 app.py &
    - name: Give output
      id: myoutput
      run: curl http://127.0.0.1:5000?input=black
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myartifact
        path: testoutput
  unit-coverage:
    runs-on: ubuntu-latest
    needs: unit-testing
    continue-on-error: false
    steps:
    - name: Checkout action at unit-coverage job
      uses: actions/checkout@v4
    - name: Install flask
      run: pip3 install flask
    - name: Installing requests module
      run: pip3 install requests
    - name: Run app
      run: python3 app.py &
    - name: Download artifact created in unit-testing job
      uses: actions/download-artifact@v4
      with:
        name: myartifact
    - name: Running Test script test.py
      id: myoutput
      run: python3 test.py
    - name: Check content of Downloaded artifact form unit-testing job
      run: cat testoutput
    - name: Upload coverage artifact report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: testoutput
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action at Docker login job
      uses: actions/checkout@v4
    - name: Try Docker login
      uses: docker/login-action@v3
      with:
        username: ${{vars.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Docker build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: ${{vars.DOCKERHUB_USERNAME}}/myworkflowappqsimage-${{github.sha}}
    - name: test python
      run: python3 app.py
    - name: Run container from image
      run: docker run -d -p 5000:5000 --name test ${{vars.DOCKERHUB_USERNAME}}/myworkflowappqsimage-${{github.sha}} 
    - name: check docker ps
      run: docker ps
    - name: check docker logs
      run: docker logs test
    - name: Test output
      run: curl http://127.0.0.1:5000?input=green
    - name: check docker logs
      run: docker logs test



