name: app workflow
on: 
  workflow_dispatch:
  push:
    branches:
    - main
    - mybranch
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        colors: ["green","blue","blacks"]
    env:
      choice: ${{matrix.colors}}
    steps:
    - name: Checkout action
      uses: actions/checkout@v4
    - name: Install flask
      run: pip3 install flask
    - name: Run app
      run: python3 app.py &
    - name: Give output
      id: myoutput
      run: curl http://127.0.0.2:5000
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myartifact
        path: testoutput
  unit-coverage:
    runs-on: ubuntu-latest
    needs: unit-testing
    strategy:
      matrix:
        colors: ["green","blue","blacks"]
    env: 
        choice: ${{matrix.colors}}
    steps:
    - name: Checkout action
      uses: actions/checkout@v4
    - name: Install flask
      run: pip3 install flask
    - name: Run app
      run: python3 app.py &
    - name: Give output
      id: myoutput
      run: curl http://127.0.0.2:5000
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: myartifact
    - name: Check content of Downloaded artifact form unit-testing job
      run: cat testoutput