name: app workflow
on: 
  workflow_dispatch:
  push:
    branches:
    - main
    - testbranch
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        colors: ["green","blue","blacks"]
    env:
      choice: ${{matrix.colors}}
    steps:
    - name: Checkout action
      uses: actions/checkout@v4
    - name: test
      run: echo "This is test message"
    - name: Install flask
      run: pip3 install flask
    - name: Run app
      run: python3 app.py &
    - name: Give output
      id: myoutput
      run: curl http://127.0.0.1:5000
    - name: check me
      run: echo "${{steps.myoutput.outputs}}"
      